import Footer from "@/components/Footer/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import CustomCursor from "@/components/Cursor/CustomCursor";
import { Kanit } from "next/font/google";

export const metadata = {
  title: "Novexis Consulting",
  description: "Generated by create next app",
};

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kanit",
});
export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${kanit.variable} min-h-screen flex flex-col`}>
        <CustomCursor />
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
